### ISSUE TITLE
Componetizacion

### ISSUE THREAD

**Issue by carlosmca44** [jenniferom/recipe-page#1]
Tienes 3 secciones las cuales se pueden descomponer en ttulo y contenido.
Puedes crear un componente que reciba como parametro title y children, el uso de este componente recomendado puede verse de la siguiente forma:
```js
<Section title="El Titulo">
    <table>
        ...
    </table>
</Section>
```

ver: https://react.dev/reference/react/Children#exposing-multiple-components

**Comment by jenniferom** [comment]
commit 7314ee65ddd60d43331d78d6ecfa91dfbe87fefa
