### ISSUE TITLE
Problema con el uso de negritas

### ISSUE THREAD

**Issue by carlosmca44** [jenniferom/recipe-page#2]
> no es habitual el uso de esta propiedad ya que impide el uso de negritas
> 
> 
> 
> revisar: https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis 

 _Originally posted by @carlosmca44 in [f6709c7](https://github.com/jenniferom/recipe-page/commit/f6709c75044c2ae5c5dfdfed25c4b2f33b9e30c5#r148922083)_

**Comment by jenniferom** [comment]
commit eeb60dba26a046688515ca74d685c15c7ea8347b
